//Copyright timeanddate.com 2021, do not use without permission
(function(){var k,g,l,m,n,p;(function(){k=function(){function e(d,c){c||(c=document);var f;if(c.querySelectorAll)return f=arrclone(c.querySelectorAll("*["+d+"]"));c=c.firstChild;var a=[];if(c){do 1==c.nodeType&&(null!=c.getAttribute(d)&&a.push(c),(f=e(d,c)).length&&(a=a.concat(f)));while(c=c.nextSibling)}return arrclone(a)}return e}();g=function(e){var d={},c=!1;return{add:function(e,a){c=!0;d[e]=a},applyBindings:function(f){if(c)return f=e("data-tad-control",f),it(f,function(a){var b=gA(a,"data-tad-control");
if(b=d[b]){var c=eval("["+gA(a,"data-tad-options")+"]")[0]||{};"undefined"===typeof a.tadControl&&(a.tadControl=new b(a,c))}}),{nodes:f}}}}(k);l=function(){return{throttle:function(e,d,c){d||(d=250);var f,a;return function(){var b=c||this,h=+new Date,q=arguments;f&&h<f+d?(clearTimeout(a),a=setTimeout(function(){f=h;e.apply(b,q)},d)):(f=h,e.apply(b,q))}},debounce:function(e,d){var c=null;return function(){var f=this,a=arguments;clearTimeout(c);c=setTimeout(function(){e.apply(f,a)},d)}}}}();m=function(){var e=
{escapeRegExp:function(d){return d.replace(/([.*+?^=!:${}()|\[\]\/\\])/g,"\\$1")},replaceToken:function(d,c,f){return d.replace(new RegExp(e.escapeRegExp(c),"g"),f)},trim:function(d){return d.replace(/^\s+|\s+$/gm,"")}};return e}();n=function(){return{removeEventListener:function(e,d,c){e.removeEventListener?e.removeEventListener(d,c):e.detachEvent&&e.detachEvent("on"+d,c)},fireEvent:function(e,d){if(document.createEvent){var c=document.createEvent("HTMLEvents");c.initEvent(d,!0,!0)}else c=document.createEventObject(),
c.eventType=d;c.eventName=d;document.createEvent?e.dispatchEvent(c):e.fireEvent("on"+c.eventType,c)}}}();p=function(e,d,c){var f=function(a,b){this._element=a;this._options=b;this._SORTABLE_CONTAINER_CLASS="tad-sortable-container";this._SORTABLE_ITEM_CLASS="tad-sortable-item";this._SORTABLE_FIXED_CLASS="tad-sortable-fixed";this._SORTABLE_ITEM_DRAG_CLASS="tad-sortable-item-drag";this._SORTABLE_PLACE_HOLDER_CLASS="tad-sortable-place-holder";this._SORTABLE_OVER_TARGET_CLASS="tad-sortable-over-target";
this._SORTABLE_ANCHOR_CLASS="tad-sortable-anchor";this._SORTABLE_ANCHOR_ONLY_CLASS="tad-sortable-anchor-only";this._MOUSE_MOVE_THRESHOLD_TIME=50;this._START_DRAG_DELAY=150;this._draggedElement=null;this._sortableElements=[];this._placeHolderElement=null;this._koObservableArray=this._dragByAnchorOnly=!1;this._currentOverTarget=null;this._currentPlaceHolderIndex=this._initialPlaceHolderIndex=-1;this._elementClickCoords=null;this._dragStarted=this._isDragging=!1;this._startDragTimeoutId=0;this._mouseUpHandlerFn=
this._mouseMoveHandlerFn=this._mouseDownHandlerFn=this._callbackScope=this._callbackFn=null;this._isOldIE=!1;this.init()};f.prototype={init:function(){this._setOptionsFromElement();ac(this._element,this._SORTABLE_ANCHOR_ONLY_CLASS,this._dragByAnchorOnly);this._isOldIE=navigator.appVersion.match(/MSIE [3-8]/);this._mouseDownHandlerFn=this._onMouseDownHandler.bind(this);ael(this._getContainer(),"mousedown",this._mouseDownHandlerFn);this._checkIfTableElement(this._getContainer())?(this._getSortingElements=
this._getTableSortingElements,this._findDraggableParent=this._findTableDraggableParent):(this._getSortingElements=this._getClassSortingElements,this._findDraggableParent=this._findClassDraggableParent)},_setOptionsFromElement:function(){"function"===typeof this._options.callback&&(this._callbackFn=this._options.callback);null!==this._options.scope&&void 0!==this._options.scope&&(this._callbackScope=this._options.scope);null!==this._options.byAnchorOnly&&void 0!==this._options.byAnchorOnly&&(this._dragByAnchorOnly=
this._options.byAnchorOnly);null!==this._options.koObservableArray&&void 0!==this._options.koObservableArray&&(this._koObservableArray=this._options.koObservableArray);null!==this._options.dragClass&&void 0!==this._options.dragClass&&(this._SORTABLE_ITEM_DRAG_CLASS=this._options.dragClass)},_getContainer:function(){if(void 0===this._element)throw Error("SortableContainerMissingException");return this._element},_checkIfTableElement:function(a){return"TBODY"===a.tagName},_getSortingElements:function(){},
_getClassSortingElements:function(){return gebc(this._SORTABLE_ITEM_CLASS,this._getContainer())},_getTableSortingElements:function(){return arrclone(this._getContainer().getElementsByTagName("TR"))},_onMouseDownHandler:function(a){var b=this,d={};if(!b._isOldIE&&0!==a.button||b._isOldIE&&1!==a.button)return!1;if(b._isDragging)b._drop();else{b._draggedElement=b._resolveEventTarget(a);if(null===b._draggedElement)return!1;ifpd(a);for(var f in a)d[f]=a[f];b._startDragTimeoutId=setTimeout(function(){try{b._onMouseUpHandlerFn=
b._onMouseUpHandler.bind(b),b._isOldIE?(b._onMouseMoveHandlerFn=b._onMouseMoveHandler.bind(b),ael(document,"mousemove",b._onMouseMoveHandlerFn),ael(document,"mouseup",b._onMouseUpHandlerFn)):(b._onMouseMoveHandlerFn=e.throttle(b._onMouseMoveHandler,b._MOUSE_MOVE_THRESHOLD_TIME,b),aelw("mousemove",b._onMouseMoveHandlerFn),aelw("mouseup",b._onMouseUpHandlerFn)),b._startDrag(b._draggedElement,d.clientX,d.clientY)}catch(r){c.removeEventListener(b._isOldIE?document:window,"mousemove",b._onMouseMoveHandlerFn),
c.removeEventListener(b._isOldIE?document:window,"mouseup",b._onMouseUpHandlerFn)}},b._START_DRAG_DELAY)}},_onMouseMoveHandler:function(a){this._dragStarted&&this._drag(this._draggedElement,a.clientX,a.clientY)},_onMouseUpHandler:function(){var a=this;try{a._drop()}catch(b){}finally{c.removeEventListener(a._isOldIE?document:window,"mousemove",a._onMouseMoveHandlerFn),c.removeEventListener(a._isOldIE?document:window,"mouseup",a._onMouseUpHandlerFn)}setTimeout(function(){a._dragStarted=!1;a._isDragging=
!1},0)},_startDrag:function(a,b,c){null!==a&&(this._sortableElements=this._getSortingElements(),this._initialPlaceHolderIndex=this._currentPlaceHolderIndex=this._getArrayIndex(this._sortableElements,a),this._elementClickCoords=this._getOffsetCoordsFromElement(a,b,c),this._updateElementDragPosition(a,b,c),this._createPlaceHolderForElement(a),ac(a,this._SORTABLE_ITEM_DRAG_CLASS,!0),this._dragStarted=!0)},_drag:function(a,b,c){this._dragStarted&&null!==this._placeHolderElement&&(this._updateElementDragPosition(a,
b,c),a=this._getDropTargetByPos(b,c),this._currentOverTarget!==a&&(ac(this._currentOverTarget,this._SORTABLE_OVER_TARGET_CLASS,!1),ac(a,this._SORTABLE_OVER_TARGET_CLASS,!0),this._currentOverTarget=a),this._movePlaceHolder(a),this._isDragging=!0)},_drop:function(){if(null!==this._draggedElement){ac(this._draggedElement,this._SORTABLE_ITEM_DRAG_CLASS,!1);ac(this._currentOverTarget,this._SORTABLE_OVER_TARGET_CLASS,!1);this._draggedElement.className=d.trim(this._draggedElement.className);this._draggedElement.removeAttribute("style");
this._koObservableArray||this._getContainer().insertBefore(this._draggedElement,this._placeHolderElement);this._removePlaceHolder();this._sortableElements=this._getSortingElements();var a=this._initialPlaceHolderIndex;var b=this._currentPlaceHolderIndex<a?this._currentPlaceHolderIndex:this._currentPlaceHolderIndex-1;this._currentOverTarget=null;a!==b&&this._executeCallbackFn(this._callbackScope,[a,b,this._draggedElement,this._sortableElements,this._getContainer(),this._callbackScope,this])}},_updateElementDragPosition:function(a,
b,c){b=this._getOffsetCoordsFromElement(this._getContainer(),b,c);ep(a,{x:b.x-this._elementClickCoords.x,y:b.y-this._elementClickCoords.y,f:!1})},_resolveEventTarget:function(a){var b=this;a=a.target||window.event.srcElement;if(b._dragByAnchorOnly&&!hC(a,b._SORTABLE_ANCHOR_CLASS))return null;""===a.id&&(a.id="target"+dt());oael(a,"click",function(a){if(b._isDragging)return ifpd(a),!1;clearTimeout(b._startDragTimeoutId);b._startDragTimeoutId=0;return!0}.bind(b));return b._findDraggableParent(a)},_findDraggableParent:function(a){},
_findClassDraggableParent:function(a){return null===a||hC(a,this._SORTABLE_CONTAINER_CLASS)||hC(a,this._SORTABLE_FIXED_CLASS)?null:hC(a,this._SORTABLE_ITEM_CLASS)?a:this._findClassDraggableParent(a.parentElement)},_findTableDraggableParent:function(a){return null===a||"TBODY"===a.tagName||hC(a,this._SORTABLE_FIXED_CLASS)?null:"TR"===a.tagName?a:this._findTableDraggableParent(a.parentElement)},_getDropTargetByPos:function(a,b){this._draggedElement.style.visibility="hidden";a=document.elementFromPoint(a,
b);this._draggedElement.style.visibility="visible";return this._findDraggableParent(a)},_getOffsetCoordsFromElement:function(a,b,c){a=ap(a,!1);return{x:b-a.x,y:c-a.y}},_createPlaceHolderForElement:function(a){this._placeHolderElement=a.cloneNode(!0);this._placeHolderElement.removeAttribute("style");ac(this._placeHolderElement,this._SORTABLE_PLACE_HOLDER_CLASS,!0);this._getContainer().insertBefore(this._placeHolderElement,a);return this._placeHolderElement},_removePlaceHolder:function(){for(var a=
gebc(this._SORTABLE_PLACE_HOLDER_CLASS,this._getContainer()),b=a.length-1;0<=b;b--)this._getContainer().removeChild(a[b]);this._placeHolderElement=null},_movePlaceHolder:function(a){var b=this._getArrayIndex(this._sortableElements,a);-1!==b&&(this._currentPlaceHolderIndex===b&&(a=this._sortableElements[b+1],b+=1),null!==this._placeHolderElement&&(a?this._getContainer().insertBefore(this._placeHolderElement,a):this._getContainer().appendChild(this._placeHolderElement),this._currentPlaceHolderIndex=
b));return this._currentPlaceHolderIndex},_executeCallbackFn:function(a,b){a=a||window;"function"==typeof this._callbackFn&&this._callbackFn.apply(a,b)},_getArrayIndex:function(a,b){for(var c=-1,d=0;d<a.length;d++)if(a[d]===b){c=d;break}return c}};return f}(l,m,n);(function(){Function.prototype.bind||(Function.prototype.bind=function(e){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var d=Array.prototype.slice.call(arguments,
1),c=this,f=function(){},a=function(){return c.apply(this instanceof f?this:e,d.concat(Array.prototype.slice.call(arguments)))};f.prototype=this.prototype;a.prototype=new f;return a})})();g.add("tadSortable",p);(function(e){function d(){e.applyBindings()}"complete"===document.readyState?d():document.addEventListener?document.addEventListener("DOMContentLoaded",d,!1):document.attachEvent("onreadystatechange",d,!1)})(g)})()})();
