//Copyright timeanddate.com 2021, do not use without permission
(function(g){function c(a){if(b[a])return b[a].exports;var f=b[a]={i:a,l:!1,exports:{}};g[a].call(f.exports,f,f.exports,c);f.l=!0;return f.exports}var b={};c.m=g;c.c=b;c.d=function(a,b,d){c.o(a,b)||Object.defineProperty(a,b,{enumerable:!0,get:d})};c.r=function(a){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})};c.t=function(a,b){b&1&&(a=c(a));if(b&8||b&4&&"object"===typeof a&&a&&a.__esModule)return a;
var d=Object.create(null);c.r(d);Object.defineProperty(d,"default",{enumerable:!0,value:a});if(b&2&&"string"!=typeof a)for(var e in a)c.d(d,e,function(e){return a[e]}.bind(null,e));return d};c.n=function(a){var b=a&&a.__esModule?function(){return a["default"]}:function(){return a};c.d(b,"a",b);return b};c.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};c.p="";return c(c.s=5)})([function(g,c){c={};window.vm?c=window.vm:window.vm=c;g.exports=c},function(g,c){ko.subscribable.fn.subscribeChanged=
function(b){var a;this.subscribe(function(b){a=b},this,"beforeChange");return this.subscribe(function(c){b(c,a)})};ko.observable.fn.withSilentUpdate=function(){this.notifySubscribers=function(){this.pauseNotifications||ko.subscribable.fn.notifySubscribers.apply(this,arguments)};this.silentUpdate=function(b){this.pauseNotifications=!0;this(b);this.pauseNotifications=!1};return this};ko.extenders.numericTime=function(b,a){var c=ko.pureComputed({read:b,write:function(d){var e=b(),m=isNaN(d)||0>d?0:parseInt(+d),
c=m;"m"===a||"s"===a?59<m&&(c=59):99<d&&(d=99);c!==e?b(c):d!==e&&b.notifySubscribers(c)}}).extend({notify:"always"});c(b());return c};ko.observableArray.fn.moveTo=function(b,a){var c=this.peek();this.valueWillMutate();b=c.splice(b,1);c.splice(a,0,b[0]);this.valueHasMutated()};ko.bindingHandlers.element={init:function(b,a){a()(b)}}},function(g,c,b){b(1);var a=b(12),f=b(3),d=b(4),e=function(b,e,c){this.label=ko.observable(b);this._autoTimeSpan=new f(0,0);this._manualTimeSpan=new f(0,0);this._progressTime=
ko.observable(0).withSilentUpdate();this._alarm=new a(e||0,c);this.status=ko.observable(1).extend({notify:"always"});this.mode=ko.observable(0).extend({notify:"always"});this.completedRatio=null;this.relativeWidth=ko.observable(1);this.relativePosition=ko.observable(0);this.isEditing=ko.observable(!1);this._alarmTriggered=!1;this.startStop=new d;this.init()};e.enums={mode:{AUTO:0,MANUAL:1},status:{STARTED:0,PAUSED:1}};e.prototype={init:function(){var a=this;a.mode.subscribe(function(b){a.setManualMode(parseInt(b)===
e.enums.mode.MANUAL)},a);a.mode(e.enums.mode.AUTO);a.label.subscribe(function(){a.onChange()},a);a._alarm.timestamp.subscribe(function(){a.onChange()},a);a._alarm.sound.subscribe(function(){a.onChange()},a);a.completedRatio=ko.computed(function(){return a.getTimeLeft()/a.getDuration()});a.completedRatio.subscribeChanged(function(b,d){0<d&&0>=b&&(a.onFinish(),a.mode()===e.enums.mode.MANUAL&&a.startStop.setToggled(!1))})},start:function(a){this.status()===e.enums.status.PAUSED&&(this._manualTimeSpan.setInitialTime(a,
!0),this._manualTimeSpan.setEndTime(a),this.status(e.enums.status.STARTED),this.mode(e.enums.mode.MANUAL))},pause:function(a){this.status()===e.enums.status.STARTED&&(this._manualTimeSpan.setEndTime(a,!0),this._progressTime.silentUpdate(this._progressTime()+this._manualTimeSpan.getIntervalTime()),this._manualTimeSpan.setInitialTime(a),this.status(e.enums.status.PAUSED))},reset:function(){this._autoTimeSpan.setInitialTime(0,!0);this._autoTimeSpan.setEndTime(0);this._manualTimeSpan.setInitialTime(0,
!0);this._manualTimeSpan.setEndTime(0);this._progressTime(0);this.status(e.enums.status.PAUSED)},setManualMode:function(a){a&&this._progressTime()<this._autoTimeSpan.getIntervalTime()&&this._progressTime(this._autoTimeSpan.getIntervalTime())},getIntervalTime:function(){return this._autoTimeSpan.getIntervalTime()},getCurrentTime:function(){return this._autoTimeSpan.getEndTime()},setCurrentTime:function(a,b){this.mode()===e.enums.mode.AUTO&&(this._autoTimeSpan.setEndTime(a),this._autoTimeSpan.getIntervalTime()>
this._progressTime()&&this._progressTime(this._autoTimeSpan.getIntervalTime()),this._manualTimeSpan.setInitialTime(b,!0));this._manualTimeSpan.setEndTime(b)},getInitialTime:function(){return this._autoTimeSpan.getInitialTime()},setInitialTime:function(a){this._autoTimeSpan.setInitialTime(a)},getEndTime:function(){return this.getDuration()+this.getInitialTime()},getDuration:function(){return this._alarm.getTimestamp()},getProgressTime:function(){return this.getDuration()-this.getTimeLeft()},getTimeLeft:function(){var a=
this.getDuration()-(this._progressTime()+this._manualTimeSpan.getIntervalTime());return a>this.getDuration()?this.getDuration():0<a?a:0},getTimeBeforeStart:function(){var a=this.getIntervalTime()+this.getProgressTime();return 0>a?-a:0},getTimeAfterEnd:function(){var a=this.getIntervalTime()-this.getDuration();return 0<a?a:0},toggleEditing:function(){this.isEditing(!this.isEditing())},onFinish:function(){return!1},onChange:function(){return!1}};g.exports=e},function(g,c,b){b(1);c=function(a,b,d){this._initialTime=
ko.observable(a).withSilentUpdate();this._endTime=ko.observable(b).withSilentUpdate();this._timeInterval=ko.observable(d).withSilentUpdate();this._init()};c.prototype={_init:function(){void 0!==this.getInitialTime()&&void 0!==this.getEndTime()&&this.setIntervalTime(this.calcIntervalTime())},getInitialTime:function(){return this._initialTime()},setInitialTime:function(a,b){b?this._initialTime.silentUpdate(parseInt(a)):this._initialTime(parseInt(a));this._endTime()&&(b?this._timeInterval.silentUpdate(this.calcIntervalTime()):
this._timeInterval(this.calcIntervalTime()))},getEndTime:function(){return this._endTime()},setEndTime:function(a,b){b?(this._endTime.silentUpdate(parseInt(a)),this._timeInterval.silentUpdate(this.calcIntervalTime())):(this._endTime(parseInt(a)),this._timeInterval(this.calcIntervalTime()))},getIntervalTime:function(){return this._timeInterval()},setIntervalTime:function(a,b){b?this._timeInterval.silentUpdate(parseInt(a)):this._timeInterval(parseInt(a))},calcIntervalTime:function(){return this._endTime()-
this._initialTime()}};g.exports=c},function(g,c){c=function(){this._isOn=ko.observable(!1);this.toggle=this._onClickHandler.bind(this)};c.prototype={_onClickHandler:function(){this.setToggled(!this._isOn())},getToggled:function(){return this._isOn()},setToggled:function(b){b?this.startCallback():this.stopCallback();this._isOn(b)},startCallback:function(){},stopCallback:function(){}};g.exports=c},function(g,c,b){function a(){f.applyBindings()}var f=b(6);b(8);"complete"===document.readyState?a():document.addEventListener?
document.addEventListener("DOMContentLoaded",a,!1):document.attachEvent("onreadystatechange",a,!1)},function(g,c,b){var a=b(7);window._T=window._T||{};window._T.controls=window._T.controls||{};var f={},d=!1;g.exports={add:function(a,b){d=!0;f[a]=b;window._T.controls[a]=b},applyBindings:function(b){if(d)return b=a("data-tad-control",b),it(b,function(a){var b=gA(a,"data-tad-control");if(b=f[b]){var d=eval("["+gA(a,"data-tad-options")+"]")[0]||{};"undefined"===typeof a.tadControl&&(a.tadControl=new b(a,
d))}}),{nodes:b}}}},function(g,c,b){var a,f;!(a=[],f=function(){function a(b,d){d||(d=document);var e;if(d.querySelectorAll)return e=arrclone(d.querySelectorAll("*["+b+"]"));d=d.firstChild;var c=[];if(d){do 1==d.nodeType&&(null!=d.getAttribute(b)&&c.push(d),(e=a(b,d)).length&&(c=c.concat(e)));while(d=d.nextSibling)}return arrclone(c)}return a}.apply(c,a),void 0!==f&&(g.exports=f))},function(g,c,b){c=b(0);b(1);b=b(9);c.app=new b;ko.applyBindings(c);g.exports=b},function(g,c,b){function a(n){a="function"===
typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};return a(n)}var f=b(10),d=b(2),e=b(13),m=b(14),l=b(15),p=b(17),r=b(3),t=b(4),h=b(0),k=function(a,b){this._element=a;this._options=b;this._soundManager=this._countdownList=null;this._localStorage=p.getLocalStorage();this._startStopButton=null;this._autoTimeSpan=new r(0,0);this._progressTime=ko.observable(0);this._addInput=
ko.observable(new d("",0,l[0]));this._currentMode=ko.observable(0);this._selectedCountdown=ko.observable(new d("",0,l[0]));this._isRunning=ko.observable(!1);this._UPDATE_INTERVAL_ID=0;this._UPDATE_INTERVAL_TIME=25;this._localStorageSaveAttribute="ot";this._isRestoring=!1;this.startStop=new t;this.fullScreenMode=ko.observable(!1);this.counter=0;this.init()};k.enums={modes:{START_ALL:0,END_TOGETHER:1,IN_SEQUENCE:2,MANUAL:3}};k.prototype={init:function(){this._registerComponents();this._registerViewModel();
this.changeMode(k.enums.modes.START_ALL);this._currentMode.subscribe(function(a){this.changeMode(parseInt(a));this._save()},this);this._restore()},_registerComponents:function(){var a=this;a.startStop.startCallback=a.start.bind(a);a.startStop.stopCallback=a.pause.bind(a);h.countdowns={};a._countdownList=new f({viewModel:h.countdowns});a._countdownList.afterRemoveItem=function(){1==a._countdownList.getCollection().length&&a.changeMode(k.enums.modes.MANUAL);a._redrawAll();a._save()}.bind(a);a._soundManager=
new e(new m(l),5)},_registerViewModel:function(){var a=this;h.addCountdown=a.addCountdown.bind(a);h.countdownHeight=ko.observable(0);h.currentMode=a._currentMode;h.formatTime=a.formatTime;h.fullScreenMode=a.fullScreenMode;h.getCountdownState=a.getCountdownState.bind(a);h.isMainRunning=a._isRunning;h.modes=k.enums.modes;h.moveTo=a.moveCountdown.bind(a);h.pauseSingle=a.pauseSingle.bind(a);h.reset=a.reset.bind(a);h.resetSingle=a.resetSingle.bind(a);h.selected=a._selectedCountdown;h.selectCountdown=a.selectCountdown.bind(a);
h.sounds=l;h.startSingle=a.startSingle.bind(a);h.startStopToggle=a.startStop.toggle;h.testSound=a._onSoundTestClick.bind(a);h.toolboxHeight=ko.observable(0);h.totalTime=ko.observable(1);h.fullScreenToggle=function(){this.fullScreenMode(!this.fullScreenMode())};h.totalTimeLeft=ko.computed(function(){var a=this.getDuration()-(this._progressTime()+this._autoTimeSpan.getIntervalTime());return 0<a?a:0},a);h.totalCompletedRatio=ko.computed(function(){var a=(this._progressTime()+this._autoTimeSpan.getIntervalTime())/
this.getDuration();return 0<a?a:0},a);h.activeIndex=ko.pureComputed(function(){return parseInt(a._currentMode())===k.enums.modes.IN_SEQUENCE?a._countdownList.getFirstActiveIndex():0},a).extend({rateLimit:{timeout:100}});h.activeIndex.subscribeChanged(function(b,d){var n=a._getCountdownHeight();a._animate(h,"toolboxHeight",d*n,b*n,20,20)})},changeMode:function(a){this._currentMode(a);switch(a){case k.enums.modes.START_ALL:this.setStart=this._setStartAllTogetherStrategy;this.update=this._updateAutoStrategy;
this._setCountdownManualMode(!1);break;case k.enums.modes.END_TOGETHER:this.setStart=this._setEndAllTogetherStrategy;this.update=this._updateAutoStrategy;this._setCountdownManualMode(!1);break;case k.enums.modes.IN_SEQUENCE:this.setStart=this._setStartInSequenceStrategy;this.update=this._updateAutoStrategy;this._setCountdownManualMode(!1);break;case k.enums.modes.MANUAL:this.setStart=this._setStartManualStrategy;this.update=this._updateManualStrategy;this._setCountdownManualMode(!0);break;default:this.setStart=
this._setStartAllTogetherStrategy,this.update=this._updateAutoStrategy,this._setCountdownManualMode(!1)}try{this.reset()}catch(q){}},setCurrentTimerOffset:function(a){var b=this._isRunning();this.pause();this._progressTime(a);b&&this.start()},setStart:function(){return!1},_setStartAllTogetherStrategy:function(){var a=this._countdownList.getMaxProgressTime();ko.utils.arrayForEach(this._countdownList.getCollection(),function(b){b.setInitialTime(a-b.getProgressTime())})},_setEndAllTogetherStrategy:function(){var a=
this._countdownList.getMaxDuration();ko.utils.arrayForEach(this._countdownList.getCollection(),function(b){b.setInitialTime(a-b.getDuration())})},_setStartInSequenceStrategy:function(){for(var a=this._countdownList.getCollection(),b=this._countdownList.getCollectionCount(),d=0,e=0;e<b;e++){if(0<e&&(d=a[e-1].getEndTime()-a[e].getProgressTime(),0>d)){for(var c=e-1;0===c;c--)a[c].setInitialTime(a[c].getInitialTime()-d);d=0}a[e].setInitialTime(d)}},_setStartManualStrategy:function(){ko.utils.arrayForEach(this._countdownList.getCollection(),
function(a){a.setInitialTime(0)})},update:function(a){return!1},currentMode:null,_updateAutoStrategy:function(a){a="undefined"===typeof a?dt():a;this._autoTimeSpan.setEndTime(a);var b=this._progressTime()+this._autoTimeSpan.getIntervalTime();ko.utils.arrayForEach(this._countdownList.getCollection(),function(d){d.setCurrentTime(b,a)});b>=this.getDuration()&&this._isRunning()&&(this.pause(),this.startStop.setToggled(!1))},_updateManualStrategy:function(a){var b=this._progressTime()+this._autoTimeSpan.getIntervalTime();
a="undefined"===typeof a?dt():a;ko.utils.arrayForEach(ko.utils.arrayFilter(this._countdownList.getCollection(),function(a){return a.mode()===d.enums.mode.MANUAL&&a.status()===d.enums.status.STARTED}),function(d){d.setCurrentTime(b,a)})},start:function(){var b=this;it(b._soundManager._soundChannels,function(b){var d=b.play();if("undefined"!==typeof d&&void 0!==a(d["catch"]))d["catch"](function(){});b.pause()});b._soundManager.play(b._soundManager.getLibrary().getFirst());b._isRunning()||(b._autoTimeSpan.setInitialTime(dt(),
!0),b._isRunning(!0),b._UPDATE_INTERVAL_ID=setInterval(function(){b.update()},b._UPDATE_INTERVAL_TIME))},pause:function(){var a=dt();this._isRunning()&&(this._isRunning(!1),clearInterval(this._UPDATE_INTERVAL_ID),this._UPDATE_INTERVAL_ID=0,this.update(a),this._progressTime(this._progressTime()+this._autoTimeSpan.getIntervalTime()),this._autoTimeSpan.setInitialTime(a))},reset:function(){this._isRunning()||(this.setCurrentTimerOffset(0),ko.utils.arrayForEach(this._countdownList.getCollection(),function(a){a.reset()}),
this._redrawAll())},startSingle:function(a){a.start(dt());this.start()},pauseSingle:function(a){a.pause(dt());ko.utils.arrayFirst(this._countdownList.getCollection(),function(a){return a.status()===d.enums.status.STARTED})||(this.pause(),this.startStop.setToggled(!1))},resetSingle:function(a){a.reset()},_setCountdownManualMode:function(a){ko.utils.arrayForEach(this._countdownList.getCollection(),function(b){b.mode(a?d.enums.mode.MANUAL:d.enums.mode.AUTO)})},setTimeOffset:function(a,b){ko.utils.arrayForEach(this._countdownList.getCollection(),
function(d){d.setCurrentTime(a,b)})},getDuration:function(){return this._currentMode()==k.enums.modes.IN_SEQUENCE?this._countdownList.getSumDuration():this._countdownList.getMaxDuration()},addCountdown:function(){var a=this._countdownList.add("Timer "+ ++this.counter,12E4,l[0]);this._registerCountdownCallbacks(a);this._redrawAll();this._save()},_registerCountdownCallbacks:function(a){var b=this;a.onFinish=function(){b._soundManager.play(this._alarm.getSound())};a.onChange=function(){b._redrawAll();
b._save()};a.startStop.startCallback=b.startSingle.bind(b,a);a.startStop.stopCallback=b.pauseSingle.bind(b,a)},selectCountdown:function(a){a.isEditing(!0);this._selectedCountdown(a)},isSelectedCountdown:function(a){return this._selectedCountdown()===a},getCountdownState:function(a){if(parseInt(this._currentMode())===k.enums.modes.MANUAL)a=1===a.completedRatio()?"waiting":0===a.completedRatio()?"done":"running";else{var b=this._progressTime()+this._autoTimeSpan.getIntervalTime();a=b<=a.getInitialTime()?
"waiting":b>=a.getEndTime()?"done":"running"}return a},formatTime:function(a,b){b=b?0:999;a=new Date((isNaN(a)?0:a)+b);b=24*(a.getUTCDate()-1)+a.getUTCHours();return p2(b)+":"+p2(a.getUTCMinutes())+":"+p2(a.getUTCSeconds())},getRelativePosition:function(a){return a.getInitialTime()/this.getDuration()},getRelativeWidth:function(a){return a.getDuration()/this.getDuration()},setAllRelativePosition:function(){var a=this;ko.utils.arrayForEach(a._countdownList.getCollection(),function(b){setTimeout(function(){a._animate(b,
"relativePosition",b.relativePosition(),a.getRelativePosition(b),20,20)},0)})},setAllRelativeWidth:function(){var a=this;ko.utils.arrayForEach(a._countdownList.getCollection(),function(b){setTimeout(function(){a._animate(b,"relativeWidth",b.relativeWidth(),a.getRelativeWidth(b),20,20)},0)})},_getCountdownHeight:function(){var a=0;try{a=gebc("c-countdown")[0].offsetHeight}catch(q){void 0}return a},_animate:function(a,b,d,e,c,f){var g=e-d;e=function(e){setTimeout(function(){var f=d+g*(-Math.pow(2,e/
c*-10)+1);if("function"===typeof a[b])a[b](f);else a[b]=f},f*e)};c=c||10;f=f||25;if(0!==g)for(var h=1;h<=c;h++)e(h)},_redrawAll:function(){this.setStart();this.setCurrentTimerOffset(this._countdownList.getFirstProgressOffset());h.totalTime(this.getDuration())},moveCountdown:function(a,b){this._countdownList.moveItem(a,b);this._redrawAll();this._save()},_onSoundTestClick:function(b){"object"===a(b[0])&&(b=b[0]);this._soundManager.play(b)},_save:function(){this._localStorage&&"undefined"!==typeof JSON&&
!this._isRestoring&&this._localStorage.setItem(this._localStorageSaveAttribute,this._serialize())},_restore:function(){this._isRestoring=!0;this._localStorage&&"undefined"!==typeof JSON&&this._deserialize(this._localStorage.getItem(this._localStorageSaveAttribute));0===this._countdownList.getCollectionCount()&&this.addCountdown();1===this._countdownList.getCollectionCount()&&this.changeMode(k.enums.modes.MANUAL);this._isRestoring=!1},_serialize:function(){var a=this;return JSON.stringify({cm:a._currentMode(),
cdl:function(){var b=[];ko.utils.arrayForEach(a._countdownList.getCollection(),function(a){b.push({lbl:a.label(),md:a.mode(),ts:a.getDuration()/1E3,sd:a._alarm.getSound().name})});return b}()})},_deserialize:function(a){var b=this,e,c=JSON.parse(a);c&&(b._countdownList.setCollection(function(){var a=[];c.cdl&&ko.utils.arrayForEach(c.cdl,function(c){e=new d(c.lbl,1E3*c.ts,b._soundManager.getLibrary().getSoundByName(c.sd));b._registerCountdownCallbacks(e);a.push(e)});return a}()),b._currentMode(c.cm),
b.counter=b._countdownList.getCollectionCount())}};g.exports=k},function(g,c,b){function a(a){this._options=a;f.apply(this,arguments);this._init()}var f=b(11),d=b(2);a.prototype=new f({extending:!0});a.prototype._init=function(){this.init()};a.prototype.add=function(a,b,c){return this.addItem(new d(a,b,c))};a.prototype.getMaxDuration=function(){return Math.max.apply(null,ko.utils.arrayMap(this.getCollection(),function(a){return a.getDuration()}))};a.prototype.getSumDuration=function(){var a=0;ko.utils.arrayMap(this.getCollection(),
function(b){a+=b.getDuration()});return a};a.prototype.getMaxTimeLeft=function(){return Math.max.apply(null,ko.utils.arrayMap(this.getCollection(),function(a){return a.getTimeLeft()}))};a.prototype.getMaxProgressTime=function(){return Math.max.apply(null,ko.utils.arrayMap(this.getCollection(),function(a){return a.getProgressTime()}))};a.prototype.getFirstProgressOffset=function(){return Math.min.apply(null,ko.utils.arrayMap(this.getCollection(),function(a){return a.getInitialTime()+a.getProgressTime()}))};
a.prototype.getMaxEndTime=function(){return Math.max.apply(null,ko.utils.arrayMap(this.getCollection(),function(a){return a.getEndTime()}))};a.prototype.getMaxDuration=function(){return Math.max.apply(null,ko.utils.arrayMap(this.getCollection(),function(a){return a.getDuration()}))};a.prototype.getFirstActiveIndex=function(){var a=this.getCollectionObservable().indexOf(ko.utils.arrayFirst(this.getCollection(),function(a){return 0<a.getProgressTime()&&a.getProgressTime()<a.getDuration()}));return-1===
a?0:a};g.exports=a},function(g,c){c=function(b){this._options=b||{};this._itemCollection=ko.observableArray();this._viewModel={};this._options.extending||this.init()};c.prototype={init:function(){this._processOptions(this._options);this._registerToViewModel(this._viewModel)},_processOptions:function(b){"undefined"!==typeof b&&"undefined"!==typeof b.viewModel&&null!==b.viewModel&&(this._viewModel=b.viewModel)},_registerToViewModel:function(b){b.list=this._itemCollection;b.removeItem=this.removeItem.bind(this)},
getCollection:function(){return this._itemCollection()},setCollection:function(b){this._itemCollection(b)},getCollectionObservable:function(){return this._itemCollection},getCollectionCount:function(){return this.getCollection().length},addItem:function(b){this._itemCollection.push(b);return b},moveItem:function(b,a){this._itemCollection.moveTo(b,a)},beforeRemoveItem:function(b,a,c,d){return!0},afterRemoveItem:function(){},removeItem:function(b){var a=this._itemCollection,c=a.indexOf(b);if(!this.beforeRemoveItem(b,
c,a(),this))return!1;a.remove(b);this.afterRemoveItem(a(),this)},removeAll:function(){this._itemCollection.removeAll()}};g.exports=c},function(g,c){c=function d(a,c){var e=this;e.hours=ko.observable(0).extend({numericTime:"h"});e.minutes=ko.observable(0).extend({numericTime:"m"});e.seconds=ko.observable(0).extend({numericTime:"s"});e.sound=ko.observable(c);e.timestamp=ko.pureComputed({read:function(){return d.hmsToTimestamp(e.hours(),e.minutes(),e.seconds())},write:function(a){a=d.timestampToHMS(a);
e.hours(a.hour);e.minutes(a.minute);e.seconds(a.second)},owner:e});e.init(a)};c.prototype={init:function(a){this.setTimestamp(a||0)},getTimestamp:function(){return this.timestamp()},setTimestamp:function(a){this.timestamp(a)},getSound:function(){var a=this.sound();"undefined"!==typeof a[0]&&(a=a[0]);return a},setSound:function(a){this.sound(a)}};c.timestampToHMS=function(a){a=new Date(a);return{hour:a.getUTCHours()+24*(a.getUTCDate()-1),minute:a.getUTCMinutes(),second:a.getUTCSeconds()}};c.hmsToTimestamp=
function(a,c,d){c=c||0;d=d||0;a=parseInt(a||0);return 1E3*(3600*(99<a?99:a)+60*parseInt(c)+parseInt(d))};g.exports=c},function(g,c,b){var a=b(0),f=function(a,b,c){this._flashElement=null;this._soundLibrary=a;this._sfxPath="sfx/";this._FLASH_ELEMENT_ID="flashAudioManager";this._support={};this._soundChannels=[];this._numSoundChannels=4;this.init(a,b,c)};f.codecNames={ogg:'audio/ogg; codecs="vorbis"',mp3:"audio/mpeg;",wav:'audio/wav; codecs="1"',m4a:"audio/x-m4a;",acc:"audio/aac;"};f.prototype={init:function(b,
c,f){void 0!==c&&(this._numSoundChannels=c);void 0!==f&&(this._sfxPath=f);this._soundLibrary=b;this._support=this.getBrowserSupport();this._processLibrary(this._soundLibrary.getSounds());this._support.html5.isAvailable?(this._soundChannels=this._createSoundChannels(this._numSoundChannels),this.play=this._playHtml5AudioStrategy,this.stop=this._stopHtml5AudioStrategy):this._support.flash.isAvailable&&(this.play=this._playFlashAudioStrategy,this.stop=this._stopFlashAudioStrategy);this._registerToViewModel(a)},
_registerToViewModel:function(a){a.hasSoundSupport=ko.observable(this._support.html5.isAvailable||this._support.flash.isAvailable)},getBrowserSupport:function(a,b){this._flashElement=gf(this._FLASH_ELEMENT_ID);return{html5:this.getHtml5Support(a||cE("audio")),flash:{isAvailable:!(!b&&!this._flashElement)}}},getHtml5Support:function(a){var b=!!a.canPlayType;return b=b?{isAvailable:!0,mp3:a.canPlayType(f.codecNames.mp3),ogg:a.canPlayType(f.codecNames.ogg),wav:a.canPlayType(f.codecNames.wav),m4a:a.canPlayType(f.codecNames.m4a)||
a.canPlayType(f.codecNames.acc)}:{isAvailable:!1}},getFileToPlay:function(a){var b=null,c=this._support.flash.isAvailable;this._support.html5.isAvailable?this._support.html5.mp3&&"undefined"!==typeof a.mp3?b=a.mp3:this._support.html5.ogg&&"undefined"!==typeof a.ogg?b=a.ogg:this._support.html5.m4a&&"undefined"!==typeof a.m4a&&(b=a.m4a):c&&"undefined"!==typeof a.mp3&&(b=this._getFlashIdFromEmbed(a.mp3));return b},_createSoundChannels:function(a){var b=[];if(this._support.html5.isAvailable)for(void 0!==
a&&(this._numSoundChannels=a),a=0;a<this._numSoundChannels;a++)b.push(new Audio);return b},getLibrary:function(){return this._soundLibrary},play:function(a){return!1},_playHtml5AudioStrategy:function(a){var b=this._getAvailableChannel();return this.loadSound(b,a)?(b.play(),!0):!1},_getAvailableChannel:function(){for(var a=0,b=0;b<this._soundChannels.length;b++)if(0===this._soundChannels[b].duration||this._soundChannels[b].paused){a=b;break}return this._soundChannels[a]},_playFlashAudioStrategy:function(a){if(null!==
a&&"undefined"!==typeof a&&this._flashElement&&this._flashElement.src){if("undefined"!==typeof a[0]&&(a=a[0]),null===a.target||"undefined"===typeof a.target)a.target=this._getFlashIdFromEmbed(a.mp3)}else return void 0,!1;this._flashElement.pplay(a.target);return!0},stop:function(){return!1},_stopHtml5AudioStrategy:function(){for(var a=0;a<this._soundChannels.length;a++)this._soundChannels[a].pause()},_stopFlashAudioStrategy:function(){"function"===typeof this._flashElement.pause&&this._flashElement.pause()},
loadSound:function(a,b){var c=!1;a&&null!==b&&null!==b.target&&"undefined"!==typeof b.target&&(a.src!==this._sfxPath+b.target&&(a.src=this._sfxPath+b.target,a.load()),c=!0);return c},_processLibrary:function(a){for(var b=0;b<a.length;b++)a[b].target=this.getFileToPlay(a[b]);return a},_getFlashIdFromEmbed:function(a){return this._flashElement&&this._flashElement.src?this._flashElement.src(this._sfxPath+a):null}};g.exports=f},function(g,c){c=function(b){this._sounds=b};c.prototype={getSounds:function(){return this._sounds},
_getSoundIndex:function(b){var a=-1;if("undefined"===typeof b||null===b)return 0;for(var c=0;c<this._sounds.length;c++)if(this._sounds[c].name===b.name){a=c;break}return a},getSoundByName:function(b){for(var a=0;a<this._sounds.length;a++)if(this._sounds[a].name===b)return this._sounds[a];return null},getFirst:function(){return this._sounds[0]}};g.exports=c},function(g,c,b){c=b(16);g.exports=[{name:"--"+c.SOUND_NAME_NONE+"--",mp3:null,ogg:null},{name:c.SOUND_NAME_BEEP,mp3:"beep-6.mp3",ogg:"beep-6.ogg"},
{name:c.SOUND_NAME_BEEP2,ogg:"Beep_1a.ogg",mp3:"Beep_1a.mp3"},{name:c.SOUND_NAME_TICK,ogg:"Tick_1a.ogg",mp3:"Tick_1a.mp3"},{name:c.SOUND_NAME_TICK2,ogg:"Tick_2a.ogg",mp3:"Tick_2a.mp3"},{name:c.SOUND_NAME_ALARM,mp3:"alarm.mp3",ogg:"alarm.ogg"},{name:c.SOUND_NAME_ALARM2,mp3:"alarm-clock-1-m.mp3"},{name:c.SOUND_NAME_CHIME,mp3:"magic-chime-01-m.mp3"},{name:c.SOUND_NAME_TELEPHONE,mp3:"telephone-ring-3.mp3"},{name:c.SOUND_NAME_TELEPHONE2,mp3:"telephone-ring-1.mp3"},{name:c.SOUND_NAME_WHISTLE,mp3:"whistle-flute-2.mp3"},
{name:c.SOUND_NAME_HORN,mp3:"bulb-horn-02.mp3"},{name:c.SOUND_NAME_BUZZER,mp3:"fail-buzzer-01.mp3"}]},function(g,c){g.exports={SOUND_NAME_NONE:"None",SOUND_NAME_BEEP:"Beep",SOUND_NAME_BEEP2:"Beep2",SOUND_NAME_TICK:"Tick",SOUND_NAME_TICK2:"Tick2",SOUND_NAME_ALARM:"Alarm",SOUND_NAME_ALARM2:"Alarm2",SOUND_NAME_CHIME:"Chime",SOUND_NAME_TELEPHONE:"Telephone",SOUND_NAME_TELEPHONE2:"Telephone2",SOUND_NAME_WHISTLE:"Whistle",SOUND_NAME_HORN:"Horn",SOUND_NAME_BUZZER:"Buzzer",BLANK:""}},function(g,c){g.exports=
{getLocalStorage:function(){a:{var b=new Date,a;try{(a=window.localStorage).setItem(b,b);var c=a.getItem(b)===b.toString();a.removeItem(b);var d=c&&a;break a}catch(e){}d=void 0}return d}}}]);
